include:
  - project: "gnome/citemplates"
    file: "flatpak/flatpak_ci_initiative.yml"

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_DEPTH: 1
    MANIFEST_PATH: "io.github.adenlall.salatok-gtk.json"
    BUNDLE: "salatok.flatpak"
    FLATPAK_MODULE: "salatok"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    APP_ID: "io.github.adenlall.salatok-gtk"

flatpak:
  extends: '.flatpak@x86_64'
  before_script:
    - flatpak --user install -y org.freedesktop.Sdk.Extension.node18//23.08 org.freedesktop.Sdk.Extension.typescript//23.08

flatpak-aarch64:
  extends: '.flatpak@aarch64'
  before_script:
    - flatpak --user install -y org.freedesktop.Sdk.Extension.node18//23.08 org.freedesktop.Sdk.Extension.typescript//23.08

nightly:
  extends: ".publish_nightly"

eslint:
  image: quay.io/fedora/fedora:latest

  variables:
    LINT_LOG: "eslint-report.txt"
  script:
    - sudo dnf install -y npm
    - npm install
    - npx eslint -o $LINT_LOG --no-color src || { cat $LINT_LOG; false; }
  artifacts:
    paths:
      - ${LINT_LOG}
    when: on_failure