name: Greetings

on: [pull_request_target, issues, fork]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
      statuses: write
      attestations: write
      discussions: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for reporting your first issue on this open source software, we will look at it as soon as possible and give you a feedback. Thank You"
        pr-message: "hank you for contributing on this open source software, we will look at it as soon as possible and give you a feedback. Thank You"
