# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request_target]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      pull-requests: write

    steps:
    - uses: mheap/github-action-required-labels@v5
      with:
        mode: minimum
        count: 2
        labels: "approved, reviewed"
    - uses: mheap/github-action-required-labels@v5
      with:
        mode: exactly
        count: 0
        labels: "buggy, awaiting, cannot merge"
        add_comment: true
        message: "This PR is being prevented from merging because you have added one of our blocking labels: {{ provided }}. You'll need to remove it before this PR can be merged."
